// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Vm_W3veM-r1TJA9feIxGu6zMOS-Adwc',
    appId: '1:430722340399:web:3a99dd0c9f4aa01f2818da',
    messagingSenderId: '430722340399',
    projectId: 'tictactoe-1295a',
    authDomain: 'tictactoe-1295a.firebaseapp.com',
    databaseURL: 'https://tictactoe-1295a-default-rtdb.firebaseio.com',
    storageBucket: 'tictactoe-1295a.firebasestorage.app',
    measurementId: 'G-66LVZWTCQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0yeqhZ3NQxS85gUYjgdklkBTvZgbdb1Y',
    appId: '1:430722340399:android:4842e5dd652cd5ae2818da',
    messagingSenderId: '430722340399',
    projectId: 'tictactoe-1295a',
    databaseURL: 'https://tictactoe-1295a-default-rtdb.firebaseio.com',
    storageBucket: 'tictactoe-1295a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcj6vmonceMD7flkI5dMZelw8QCqfthNI',
    appId: '1:430722340399:ios:6c879a32dbd26df92818da',
    messagingSenderId: '430722340399',
    projectId: 'tictactoe-1295a',
    databaseURL: 'https://tictactoe-1295a-default-rtdb.firebaseio.com',
    storageBucket: 'tictactoe-1295a.firebasestorage.app',
    iosClientId: '430722340399-8btareflnilcbogs1ilgdo0qtflolsle.apps.googleusercontent.com',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcj6vmonceMD7flkI5dMZelw8QCqfthNI',
    appId: '1:430722340399:ios:6c879a32dbd26df92818da',
    messagingSenderId: '430722340399',
    projectId: 'tictactoe-1295a',
    databaseURL: 'https://tictactoe-1295a-default-rtdb.firebaseio.com',
    storageBucket: 'tictactoe-1295a.firebasestorage.app',
    iosClientId: '430722340399-8btareflnilcbogs1ilgdo0qtflolsle.apps.googleusercontent.com',
    iosBundleId: 'com.example.game',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Vm_W3veM-r1TJA9feIxGu6zMOS-Adwc',
    appId: '1:430722340399:web:6777bc9679e8b4842818da',
    messagingSenderId: '430722340399',
    projectId: 'tictactoe-1295a',
    authDomain: 'tictactoe-1295a.firebaseapp.com',
    databaseURL: 'https://tictactoe-1295a-default-rtdb.firebaseio.com',
    storageBucket: 'tictactoe-1295a.firebasestorage.app',
    measurementId: 'G-MDMNPR54JK',
  );
}
